require: rubocop-rails

inherit_from: .rubocop_todo.yml

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - lib/tasks/auto_annotate_models.rake
    - app/api/api/v10/links.rb

Rails/SkipsModelValidations:
  Exclude:
    - app/controllers/redirects_controller.rb

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - app/api/**/*.rb

